[tool.mypy]
enable_error_code = "ignore-without-code"
exclude = [
    "alembic",
    "venv",
]
strict_optional = true
strict_equality = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
plugins = [
    "pydantic.mypy",
    "sqlalchemy.ext.mypy.plugin",
]

[[tool.mypy.overrides]]
module = "tests.*"
disable_error_code = [
    "attr-defined",
    "call-arg",
]

[tool.ruff]
# Set the maximum line length to 79.
line-length = 120

[tool.ruff.lint]
select = [
    "A",
    "B",
    "C4",
    "COM",
    "E",
    "F",
    "G",
    "I",
    "N",
    "Q",
    "PIE",
    "PT",
    "SIM",
    "TD",
    "TID",
    "T10",
    "T20",
    "UP",
    "W",
]
ignore = [
    "G010",
    "COM812",
    "Q001",
]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
    "Depends",
    "fastapi.Depends",
    "fastapi.params.Depends",
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
docstring-quotes = "double"
multiline-quotes = "single"